### ISSUE TITLE
Workaround for memory cards.

### ISSUE THREAD

**Issue by davidlares** [LudovicRousseau/pyscard#104]
Hello

Thanks for this amazing tool.

After trying a lot of mentioned configurations and reading almost all the issues of the repository based on 'Unresponsive/Unpowered cards', is there any workaround o any recommendation/tool/lecture to memory cards to follow through?

Kind regards.

DL.

**Comment by LudovicRousseau** [comment]
Memory cards are NOT smart cards.
They are not supported.
