### ISSUE TITLE
no reconnect method for CardConnection

### ISSUE THREAD

**Issue by ElouanPetereau** [LudovicRousseau/pyscard#107]
Hello,

I was wondering why no reconnect method was available for `CardConnection()`.

After I gave a look at the `winscard.h` API It seems that the behaviour of reconnect is not the same as doing a disconnect/connect so I can't do that using the disconnect then the connect methods of the higher level Python framework.
Of course I can do a Reconnect using the wrapping of the WinSCard API but it would be easier if it was implemented in `CardConnection()`.

Is there a reason why this method is not present or is it just that it wasn't requested/used by anyone?

**Comment by LudovicRousseau** [comment]
It was never requested.
Feel free to propose a patch.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/pyscard/commit/a4a030587e316427b1487eb08da2773e478d95fc
