### ISSUE TITLE
No build artifacts for Python 3.9

### ISSUE THREAD

**Issue by agmlego** [LudovicRousseau/pyscard#112]
#### Your system information

* Operating system used: Windows 10 x64
* pyscard version: 2.0.0
* Python version: 3.9.0 x64

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
`pip install pyscard` should install the artifacts for Python 3.9

Describe what _did_ happen.
pip fails, looking for swig and a compiler.

**Comment by LudovicRousseau** [comment]
https://pypi.org/project/pyscard/#files does not yet provide pre-compiled version for Python 3.9.
AppVeyor provides Python 3.9.
I tried to add a build with Python 3.9 but it fails with problem related to Windows, not PySCard. And Windows is far from my preferred OS.

Help would be greatly appreciated.
I debug AppVeyor build in https://github.com/LudovicRousseau/pyscard-debug/commits/master

**Comment by LudovicRousseau** [comment]
It should be fixed now.
