### ISSUE TITLE
RFE: provide sphinx documentation 

### ISSUE THREAD

**Issue by kloczek** [LudovicRousseau/pyscard#116]
Looks like pyscard to generate documentation uses epydoc which seems is no longer maintained.
I think that it would be good provide generated documentation using sphinx

**Comment by LudovicRousseau** [comment]
The documentation is already using sphinx. See the bottom line of https://pyscard.sourceforge.io/

The epidoc directory is no more used. I just removed it.
Thanks

**Comment by LudovicRousseau** [comment]
Have a look at https://github.com/LudovicRousseau/pyscard/tree/master/smartcard/doc

What is this file `copy.py`?
