### ISSUE TITLE
No pyscard support for Python 3.10

### ISSUE THREAD

**Issue by n-dusan** [LudovicRousseau/pyscard#122]
#### Your system information

* Operating system used: Windows 10 x64
* pyscard version: pyscard 2.0.2
* Python version: 3.10.0 x64

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

- https://pypi.org/project/pyscard/#files does not yet provide pre-compiled wheel for Python 3.10.
- AppVeyor provides Python 3.10.

Describe what _did_ happen.

`pip install pyscard` should install on Python 3.10

#### Steps for reproducing this issue:

1.  Installation fails, swig error.

Would you be interested in adding an action to automatically build wheels on tag and upload to github release and/or pypi?
Could I enhance it to include python 3.10 in all the build matrices, and submit a PR?

Thank you so much.

**Comment by LudovicRousseau** [comment]
A PR is always welcome.
Please do.

**Comment by LudovicRousseau** [comment]
You can get a build for Python 3.10 at https://ci.appveyor.com/project/LudovicRousseau/pyscard/build/job/hwiwawhxghawnf66/artifacts

I will upload the `.whl` at [pypi.org](https://pypi.org/project/pyscard/#files) for the next pyscard version.
