### ISSUE TITLE
Is it possible to fetch a One-Time Password with this package?

### ISSUE THREAD

**Issue by lucharo** [LudovicRousseau/pyscard#126]
#### Your system information

* Operating system used: Windows Version 1909 
* pyscard version: 2.0.2
* Python version: 3.9.7

#### Please describe your issue in as much detail as possible:
I would like to retrieve a One-Time Password (OTP) from a Broadcom Corp Smartcard reader.

**Comment by LudovicRousseau** [comment]
Yes, it is.
You will have to send the correct APDU commands to your card.

https://ludovicrousseau.blogspot.com/2020/11/how-to-get-smart-card-support.html
