### ISSUE TITLE
Build job: Artefacts are not downloadable

### ISSUE THREAD

**Issue by krabbenprgr** [LudovicRousseau/pyscard#140]
Can you please make a new build on AppVeyor. The last build is too long ago so that the artefacts are no longer downloadable.

Thanks in advance!

**Comment by LudovicRousseau** [comment]
You can find Windows builds on https://pypi.org/project/pyscard/#files

Does that solve your problem?

**Comment by krabbenprgr** [comment]
Yes thank you!
But now i have another problem:

NFC channel search error: cannot import name '_scard' from partially initialized module 'smartcard.scard' (most likely due to a circular import)

Thanks in advance

**Comment by krabbenprgr** [comment]
Solved the problem by installing the miniconda environment.
