### ISSUE TITLE
Missing source release for 2.0.4?

### ISSUE THREAD

**Issue by dainnilsson** [LudovicRousseau/pyscard#141]
Hello! I think the source release is missing for 2.0.4 on pypi.org. Compare:

2.0.4: https://pypi.org/project/pyscard/2.0.4/#files
2.0.3: https://pypi.org/project/pyscard/2.0.3/#files

This makes installation fail on a MacOS where I'm trying to build a universal2 binary (2.0.3 succeeds).

**Comment by LudovicRousseau** [comment]
Yes I know. It is a mistake on my side.
I uploaded a bogus version of the source code, removed it but I can't upload a new version with the same name.

You can get it at https://sourceforge.net/projects/pyscard/files/pyscard/pyscard%202.0.4/

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2022/09/pyscard-205-released.html
