### ISSUE TITLE
pyscard 2.0.4 not available on linux from pypi

### ISSUE THREAD

**Issue by engnatha** [LudovicRousseau/pyscard#142]
#### Your system information

* Operating system used:
ubuntu 20.04
* pyscard version:
2.0.4
* Python version:
3.8.10

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
I should be able to `pip install pyscard==2.0.4` as is possible with other versions.

Describe what _did_ happen.
```
ERROR: Could not find a version that satisfies the requirement pyscard==2.0.4 (from versions: 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
ERROR: No matching distribution found for pyscard==2.0.4
```

#### Steps for reproducing this issue:

1. `pip install pyscard==2.0.4`

**Comment by engnatha** [comment]
It's worth noting that https://pypi.org/project/pyscard/ points to 2.0.4 and has Unix listed as a supported operating system. It seems from past tickets that there's aversion to supporting wheel distributions for multiple operating systems.

**Comment by LudovicRousseau** [comment]
https://ludovicrousseau.blogspot.com/2022/09/pyscard-205-released.html

I provide source code. I also provide a wheel distribution for some Windows versions
I do not plan to a provide a wheel distribution for all possible combinations.

**Comment by engnatha** [comment]
Thanks for the explanation in the blog and your effort in this project!
