### ISSUE TITLE
Download artifacts for Windows

### ISSUE THREAD

**Issue by bittner** [LudovicRousseau/pyscard#147]
It's hard to find information about how to install pyscard for Windows.

In order for my colleagues to install software that builds on pyscard, I have started to point them to AppVeyor – until I found out today that the artifacts for even the latest build are deleted after a month.

> Download the latest pyscard MSI matching your Python version from their [AppVeyor](https://ci.appveyor.com/project/LudovicRousseau/pyscard) in the "Artifacts" tab of the latest build, and install it.

Now I figured out that you already use GitHub Actions, and that you [upload artifacts](https://github.com/LudovicRousseau/pyscard/blob/master/.github/workflows/windows.yml#L44-L46) of successful Windows builds. These artifacts can be found later at the bottom of the [Actions Windows Build](https://github.com/LudovicRousseau/pyscard/actions/runs/3813220378) job page, e.g.

![image](https://user-images.githubusercontent.com/665072/220162604-60cfd87a-9532-44f3-8edd-1df565e43ab3.png)

In order to make finding this easier I would suggest to:

1. Add installation or download instructions for Windows to the README (or a better-suited place in the documentation)
2. Optionally, or alternatively, upload all artifacts, including the Windows binaries, to the [release entries](https://github.com/LudovicRousseau/pyscard/releases).

**Comment by LudovicRousseau** [comment]
I provide pre-build Windows binaries from pypi at https://pypi.org/project/pyscard/#files
You can install them using `pip`.

Isn't that sufficient?

**Comment by bittner** [comment]
For everyone coming here in search of the MSI or EXE installer: Be aware that, depending on your Python setup, using them might cause dependency problems (e.g. `ModuleNotFoundError: No module named 'smartcard'`).

Use `python -m pip install pyscard` instead for a much more stable experience.
