### ISSUE TITLE
Typo in some method names in documentation

### ISSUE THREAD

**Issue by antonio-fr** [LudovicRousseau/pyscard#159]
Affecting
SCardEstablishConteYt
SCardIsValidConteYt
SCardReleaseConteYt

Example
https://github.com/LudovicRousseau/pyscard/blob/master/smartcard/scard/scard.i#L89

I guess some aggressive replacing led to that. Or am I missing something else?

**Comment by LudovicRousseau** [comment]
The bug was added in https://github.com/LudovicRousseau/pyscard/commit/8512d7a939488d0ef7946dd8f791d8fb9159b8f8 
It was 8 years ago :-)
Thanks
