### ISSUE TITLE
python3 -m pip install pyscard fails on MacOS

### ISSUE THREAD

**Issue by BMW1Addict** [LudovicRousseau/pyscard#160]
#### Your system information

* Operating system used: MacOS
* pyscard version: Trying to install latest version
* Python version: 3.11.4

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.
simply typed python3 -m pip install pyscard from MacOS terminal and received the following error:

Describe what _did_ happen.
python3 -m pip install pyscard
Collecting pyscard
  Using cached pyscard-2.0.7.tar.gz (152 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyscard
  Building wheel for pyscard (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyscard (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'smartcard.scard._scard' extension
      swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
      swig -python -outdir smartcard/scard -DPCSCLITE -D__APPLE__ -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
      error: command 'swig' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscard
Failed to build pyscard
ERROR: Could not build wheels for pyscard, which is required to install pyproject.toml-based projects

#### Steps for reproducing this issue:

1. python3 -m pip install pyscard

**Comment by LudovicRousseau** [comment]
The error is obvious:
```
 error: command 'swig' failed: No such file or directory
```

Install swig and try again. You can use [homebrew](https://brew.sh/).

For macOS pypi only provides a binary for Python 3.9, not 3.11.
https://pypi.org/project/pyscard/#files

**Comment by mbokil** [comment]
In case you are looking for the install commands here they are:
```
# Install Brew 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install SWIG
brew install swig
```
