### ISSUE TITLE
drop deprecated use of `imp`

### ISSUE THREAD

**Issue by eworm-de** [LudovicRousseau/pyscard#161]
#### Your system information

* Operating system used: Arch Linux
* pyscard version: 2.0.7-1
* Python version: 3.12

#### Please describe your issue in as much detail as possible:

The `imp` module has been removed in python 3.12. It is still used in the project, blocking the downstream python update. Please update to use `importlib` instead.

https://docs.python.org/dev/whatsnew/3.12.html#imp

#### Steps for reproducing this issue:

1. use python 3.12
2. try to use pyscard

**Comment by LudovicRousseau** [comment]
Can you provide the full error message you get?

**Comment by eworm-de** [comment]
Actually I do not yet have a package around. We are about to push this to our repositories. This is our todo list, I think this is public and you should have access: https://archlinux.org/todo/imp-module-removal-in-python-312/

The deprecated/removed module is imported in `smartcard/wx/__init__.py`, and later on `imp.is_frozen()` is called.
