### ISSUE TITLE
The Smart Card Resource Manager is not running.  (0x8010001D)

### ISSUE THREAD

**Issue by syariffortask** [LudovicRousseau/pyscard#168]
#### Your system information

* Operating system used: windows 11
* pyscard version:2.0.8
* Python version: 3.11.8

#### Please describe your issue in as much detail as possible:
The Smart Card Resource Manager is not running.  (0x8010001D)

Describe what _did_ happen.

I was confused because there was an error: Failed to establish context: The Smart Card Resource Manager is not running. (0x8010001D), but I have run the smartcard service on windows service, can it help me

#### Steps for reproducing this issue:

and this is my code. 

```
from smartcard.Exceptions import NoCardException
from smartcard.System import readers
from smartcard.util import toHexString

try:
    available_readers = readers()
    if not available_readers:
        print("Tidak ada pembaca kartu pintar yang tersedia.")
    else:
        for reader in available_readers:
            try:
                connection = reader.createConnection()
                connection.connect()
                
                atr = toHexString(connection.getATR())

                print("Pembaca:", reader)
                print("ATR:", atr)
            except NoCardException:
                print("Pembaca:", reader)
                print("Tidak ada kartu yang dimasukkan.")
except Exception as e:
    print("Terjadi kesalahan:", e)
```

**Comment by LudovicRousseau** [comment]
What did you do to get the error?
Have you removed the reader?

See also https://github.com/LudovicRousseau/pyscard/issues/136 https://github.com/LudovicRousseau/pyscard/issues/153

**Comment by syariffortask** [comment]
1. I use the ACS 120U reader, I want to learn to use the Smartcard Reader in my Python program, but when I run the program to see the available readers I get this error

 2. Yes, I have removed the reader

**Comment by LudovicRousseau** [comment]
You get the error AFTER you removed the reader?

Please describe exactly what you do and what you get.

**Comment by syariffortask** [comment]
I have run my code with the smartcard reader plug in my computer's USB port, but when I run my program above there is an error,

**Comment by LudovicRousseau** [comment]
The error is returned by Windows itself.
Maybe you reader driver is not installed or something like that.

**Comment by LudovicRousseau** [comment]
I can't help on Windows.
Maybe ACS can provide some support.

**Comment by mbokil** [comment]
Windows requires the Smart Card service to be running. Sometimes you have to enable it before you can communicate to a NFC reader. https://answers.microsoft.com/en-us/windows/forum/all/smartcard-resource-manager-is-not-running/b9aefb42-9d43-4356-8d63-341d2b1bba4a

**Comment by syariffortask** [comment]
I've already runing smart card service

**Comment by mbokil** [comment]
One other thing with Windows we found is after the user plugs in the NFC reader we always have them restart. We found the device drivers that install via plug and play often times need to be restarted. Then Python will be able to communicate to the device via SWIG.

**Comment by syariffortask** [comment]
still can't solve this isue, anybody can help please

**Comment by LudovicRousseau** [comment]
@syariffortask have you asked Microsoft?
You've bought a Windows license, so you should receive technical support for Windows-related problems. No ?

**Comment by syariffortask** [comment]
I have already ask Microsoft but Microsoft still can't reply my message

**Comment by LudovicRousseau** [comment]
This is a Windows issue.
PySCard can't fix it.
