### ISSUE TITLE
Python 3.4 Install

### ISSUE THREAD

**Issue by MaxLFarrell** [LudovicRousseau/pyscard#17]
Using
`python setup.py install`
from the github repository I am getting:
`error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).`

Is there any precompiled binary or VS project files I could use to install?

**Comment by LudovicRousseau** [comment]
Maybe you should install Microsoft Visual C++ 10.0?

I do not provide Windows binary.
You can get Continuous Integration build from https://ci.appveyor.com/project/LudovicRousseau/pyscard

**Comment by MaxLFarrell** [comment]
Thanks, the appveyor build worked perfectly.
