### ISSUE TITLE
"Issue: Unable to Read Credit Card Details from Apple Wallet Using NFC"

### ISSUE THREAD

**Issue by vijay-cg** [LudovicRousseau/pyscard#171]
#### Your system information

**Operating system used:** Windows  
**pyscard version:** 2.0.2  
**Python version:** 3.12.4  

---

**Expected behavior:**  
I expected to successfully read credit card details from Apple Wallet using NFC.

**Actual behavior:**  
However, I encountered an issue where I cannot read the card details from Apple Wallet.
'non-hexadecimal number found in fromhex() arg at position 73. NoneType' object has no attribute 'find'."

---

**Steps to reproduce:**

1. Add a credit card to Apple Wallet.
2. Attempt to tap on the NFC reader.

**Comment by LudovicRousseau** [comment]
Maybe you could include your program source code.
And the complete exception trace.

**Comment by LudovicRousseau** [comment]
No feedback from user.
Closing
