### ISSUE TITLE
Device not found on Ubuntu

### ISSUE THREAD

**Issue by leof2333** [LudovicRousseau/pyscard#172]
#### Your system information

* Operating system used: Ubuntu22.04
* pyscard version: Newest
* Python version: 3.10.12

#### Please describe your issue in as much detail as possible:
I can find my device using readers on Windows, but it fails on Ubuntu
![image](https://github.com/user-attachments/assets/3784ff9c-e3b0-475c-8b68-afdc68525658)
![image](https://github.com/user-attachments/assets/5d2a89a9-a644-46c7-ab50-c43e0d28cd54)
I don't know why

**Comment by LudovicRousseau** [comment]
You need to install the reader driver, like libacsccid1 or libccid.
See https://blog.apdu.fr/posts/2014/03/level-1-smart-card-support-on-gnulinux/

It is NOT a PySCard problem.

**Comment by leof2333** [comment]
> You need to install the reader driver, like libacsccid1 or libccid. See https://blog.apdu.fr/posts/2014/03/level-1-smart-card-support-on-gnulinux/
> 
> It is NOT a PySCard problem.


you are right, thank you
