### ISSUE TITLE
Use a `src/` layout

### ISSUE THREAD

**Issue by kurtmckee** [LudovicRousseau/pyscard#180]
Hello @LudovicRousseau!

While working on expanding the test suite to test Python 3.8 and higher, I've bumped into a classic problem. When tox runs the test suite,

1. Tox builds the smartcard package and installs it in a subdirectory in `.tox/{environment}/`
2. Tox runs the test suite, using the repository root as the current working directory
3. Python looks in the current working directory first for imports and finds `smartcard` there
4. Imports immediately fail because `smartcard/scard/_scard.{cpython-version}.so` doesn't exist
5. The test suite run fails

This is a common problem in the Python community, and the common solution is to use a `src/` layout (examples: [pytest](https://github.com/pytest-dev/pytest/), [tox](https://github.com/tox-dev/tox)). Doing so prevents Python from finding the package in the repository root at step 3, above.

Mechanically, this change would look like:

```bash
mkdir src/
git mv smartcard/ src/
# edit some paths in setup.py, .gitignore, and elsewhere
git commit -am 'Use a `src/` layout'
```

I've tested and confirmed that this change resolves `ImportError` exceptions that prevent the test suite from running on freshly-cloned repositories when invoking `tox`.

Using a `src/` layout is the well-known solution to this well-known problem, but I wanted to ask if this is acceptable to you before submitting a PR for this.

**Comment by LudovicRousseau** [comment]
Yes, I know this issue.
I also think using `src/` is the correct solution.

**Comment by kurtmckee** [comment]
I'll submit as small a PR as I can to address this.
