### ISSUE TITLE
The SCard's error is not correctly treated on non-English environment

### ISSUE THREAD

**Issue by yuki-js** [LudovicRousseau/pyscard#219]
#### Your system information

* Operating system used: Windows 11 Japanese
* pyscard version: 2.1.1
* Python version: 3.11.9

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

`SCardGetErrorMessage` work without any unhandled exception even on Japanese environment.

Describe what _did_ happen.

`UnicodeDecodeError` occurs.

```
Traceback (most recent call last):
  File "c:\Users\user\codes\sc-tools\mynatest\errorkaiseki.py", line 3, in <module>
    smartcard.scard.SCardGetErrorMessage(hr)
  File "C:\Users\user\codes\sc-tools\.venv\Lib\site-packages\smartcard\scard\scard.py", line 1196, in SCardGetErrorMessage
    return _scard.SCardGetErrorMessage(lErrCode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1250.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 0: character maps to <undefined>
```

#### Steps for reproducing this issue:

1. Set the display language to Japanese and install ローカルエクスペリエンスパック
2. Run `python3 -m venv .venv`, `.\.venv\Scripts\activate`,`pip install pyscard` on PowerShell in series
3. Run the following code
```python
import smartcard
hresult_expect = -2146435025
smartcard.scard.SCardGetErrorMessage(hresult_expect)
```

#### Root cause

7cd53116649f3c12af65d17b6b65bfeb3940b3c2 added the string conversion on Windows, but only CP1250 is considered.

I can come up with how to fix it but I am not so familiar with Windows APIs. Does anyone help with it?

When I forcefully change `encoding = "cp932"` via debugger, I got the value shown below.
![image](https://github.com/user-attachments/assets/12f00d9c-4ba1-40df-9beb-6ea5e2c68ec1)

**Comment by LudovicRousseau** [comment]
That would also explain why the error messages in French have accented letters "corrupted".

What should the code use instead of `"cp1250"`?
Does Windows uses UTF-8 or UTF-16 or whatever by default?

**Comment by yuki-js** [comment]
Windows has a long history and a long list of character encodings. Also there is a beta option to use UTF-8. I don't know how to detect it correctly.

**Comment by yuki-js** [comment]
There should be some functions to determine the current language and codepage. But I am not familiar with them, so I'd like some other person better than me to work on. (If no one here, I will try with ChatGPT)

**Comment by LudovicRousseau** [comment]
This should be fixed with https://github.com/LudovicRousseau/pyscard/commit/9d0d66554b859e6460e0360bde97c875784c1ffc

Please test and confirm if it works for you.

**Comment by yuki-js** [comment]
@LudovicRousseau 
I confirmed the conversion worked fine. Closing the issue as resolved.

```
(.venv) PS C:\Users\user\codes\sc-tools> sc-explorer select-df A000000527210101
Traceback (most recent call last):
(snip)
  File "C:\Users\user\codes\sc-tools\.venv\Lib\site-packages\smartcard\CardConnectionDecorator.py", line 66, in getATR
    return self.component.getATR()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\codes\sc-tools\.venv\Lib\site-packages\smartcard\pcsc\PCSCCardConnection.py", line 234, in getATR
    raise CardConnectionException(
smartcard.Exceptions.CardConnectionException: Failed to get status: 指定された読み取り装置は現在、利用できません。 : 指定された読み取り装置は現在、利用できません。  (0x80100017)
```
---
BTW I learned about matters about Windows' language and found the following line. 

https://github.com/LudovicRousseau/pyscard/blame/e1aa74363897cbd6dac4f5820b230fca09b20a27/smartcard/scard/scard.i#L809

I can change the error language by changing the locale constant.

```diff
-            MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
+            MAKELANGID(LANG_ENGLISH, SUBLANG_ENGLISH_US),
```

```
  File "C:\Users\user\codes\sc-tools\.venv\Lib\site-packages\smartcard\pcsc\PCSCCardConnection.py", line 130, in connect
    raise NoCardException("Unable to connect", hresult=hresult)
smartcard.Exceptions.NoCardException: Unable to connect: The smart card has been removed, so that further communication is not possible.  (0x80100069)
```

I'll note here for reference.

**Comment by LudovicRousseau** [comment]
Thanks for your feedback.
