### ISSUE TITLE
I am receiving a smartcard.Exception 

### ISSUE THREAD

**Issue by mireianogue** [LudovicRousseau/pyscard#221]
#### Your system information

* Operating system used: 11th Gen Intel® Core™ i5-11500 @ 2.70GHz × 12 with Ubuntu 20.04.5 LTS
* USB SIM Reader: Gemalto USB Shell tocken V2 
* pyscard version: pyscard-2.2.0 dist-info
* Python version: 3.9
* I'm using pySim to program a sysmocom-SJA5 sim. 

#### Please describe your issue in as much detail as possible:
I expect to see this:
![image](https://github.com/user-attachments/assets/6bcf389d-dfb3-4600-8ccf-5ba5cf5e67ef)
![image](https://github.com/user-attachments/assets/29bc38ff-6724-4466-9b70-d46ffae891d2)

Describe what _did_ happen.
Once I launch pySim-shell.py -p 0 I get the following:
![image](https://github.com/user-attachments/assets/ad6a1c91-1113-4547-a928-dd365324d6ef)
![image](https://github.com/user-attachments/assets/3fe11f3b-51d0-4cf1-8acb-0b1d7000b515)

#### Steps for reproducing this issue:

There is any solution for that? I have been reading that is an error at the PC/SC level that calls a smartcard.Exceptions, maybe it is some issue with pyscard dependencies?

Thanks for your help, in advance!

**Comment by LudovicRousseau** [comment]
It is an error reported by pcsc-lite during a SCardTransmit() call.
It is not a problem caused by PySCard.

You should have a look at the communication between the card and the reader.

**Comment by mireianogue** [comment]
Yes thank you! I have alredy solved my problem.

**Comment by LudovicRousseau** [comment]
Great
