### ISSUE TITLE
Exception ListReadersException: ('Failed to list readers', 2148532253) spam after pcscd service stop.

### ISSUE THREAD

**Issue by valdur55** [LudovicRousseau/pyscard#23]
Hi, 
As using http://pyscard.sourceforge.net/user-guide.html#monitoring-smart-cards and sending machine to reboot causes traceback spam in terminal.
After pcscd service stop, app will spam same traceback message endlessy or until app closes.

In other hand, http://pyscard.sourceforge.net/user-guide.html#monitoring-readers will give only one traceback and not more.

Digging into code  gives answer for problem:
It will spam forever: https://github.com/LudovicRousseau/pyscard/blob/defecae038d55cba4431c8e6ba68a843568ce1a9/smartcard/CardMonitoring.py#L191

It gives one traceback: https://github.com/LudovicRousseau/pyscard/blob/defecae038d55cba4431c8e6ba68a843568ce1a9/smartcard/ReaderMonitoring.py#L194

Simple fix for problem:  #22

**Comment by LudovicRousseau** [comment]
#22 merged
Thanks
