### ISSUE TITLE
Install pyscard in windows

### ISSUE THREAD

**Issue by Jenny9998877** [LudovicRousseau/pyscard#26]
Hi, I didn't see any exe or msi file for pyscard 1.9. May I ask how should I install it in windows?

Thank you
Jenny

**Comment by 50thomatoes50** [comment]
if you have pip installed just type `pip install pyscard`

if not go to
https://ci.appveyor.com/project/LudovicRousseau/pyscard
Select your python version and your system/python arch
And them click on Artifact do get the list of generated files.

**Comment by lmiguelmh** [comment]
As you can see there is no artifact for python3.5. I installed swig and used VS2015 to compile and install pyscard (python setup.py install). Now I am having this problem https://github.com/LudovicRousseau/pyscard/issues/11

**Comment by LudovicRousseau** [comment]
I modified the AppVeyor configuration to add Python 3.5.

**Comment by i2gor87** [comment]
AppVeyor compiling Python3.5x64 fails with:

`LINK : fatal error LNK1117: syntax error in option 'MANIFEST:EMBED,ID=2'
error: command 'c:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1117
Command exited with code 1`

**Comment by LudovicRousseau** [comment]
I have no idea what is wrong for Python35-x64. I suspect a transient problem at AppVeyor.

**Comment by LudovicRousseau** [comment]
I do not provide binary installers.
If you can't install PySCard using pip then open a new issue.
