### ISSUE TITLE
pyscard and OSX

### ISSUE THREAD

**Issue by miohtama** [LudovicRousseau/pyscard#35]
I am trying to get pyscard to run under OSX. I have successfully managed to get it run under Linux VM on the same computer using a USB based reader.

However on native OSX I cannot make pyscard to find my reader. 

Are there any up-to-date instructions what native dependencies and setup pyscard needs in order to run under OSX (10.11.6).

**Comment by miohtama** [comment]
This might not be the right forum to ask these questions. But basically I want to figure out

* How can I tell if OSX recognizes my reader

* What command line tools I can use to check if OSX and reader recognize the cards inserted in the reader

**Comment by LudovicRousseau** [comment]
First step is to follow https://ludovicrousseau.blogspot.fr/2014/03/level-1-smart-card-support-on-mac-os-x.html

**Comment by miohtama** [comment]
The reader is picked up by system:

<img width="611" alt="image" src="https://cloud.githubusercontent.com/assets/49922/21593617/b9c71e64-d0de-11e6-91ad-5e1c2beee35b.png">

But `pcsctest` doesn't go beyond `Testing SCardGetStatusChange`:

<img width="406" alt="image" src="https://cloud.githubusercontent.com/assets/49922/21593628/ccb8a15a-d0de-11e6-8bfe-dbdc3f13f769.png">

I sent email to the vendor support to see if they can help.

**Comment by LudovicRousseau** [comment]
Your device should be supported by the CCID driver provided by Apple.
Contacting Identive for support is a good idea.

It is not a issue with PySCard. Closing.

**Comment by miohtama** [comment]
Ok thank you for your kind help. 

One more question: How can I check the device CCID and whether it is supported by Apple?

**Comment by LudovicRousseau** [comment]
macOS Sierra provides CCID driver version 1.4.24
https://ludovicrousseau.blogspot.fr/2016/09/macos-sierra-and-smart-cards-status.html

So any reader supported in version 1.4.24 or earlier should work.
https://pcsclite.alioth.debian.org/ccid/release.html is sorted by releaser version.

**Comment by miohtama** [comment]
@LudovicRousseau you are golden.

**Comment by miohtama** [comment]
Found my hardware on shouldwork list. Also the driver runs fine on Ubuntu/Debian on the same hardware. Will dig deeper, thanks.

**Comment by miohtama** [comment]
The issue was solved with a third party driver supplied by Identiv support.

For the records the link to the driver is: http://files.identiv.com/products/smart-card-readers/common-drivers/uTrust_MAC_Driver.zip
