### ISSUE TITLE
signed releases

### ISSUE THREAD

**Issue by eworm-de** [LudovicRousseau/pyscard#38]
Version 1.9.4 shipped with a gpg signature to verify source tarball. We already used this to verify source when building the Arch Linux package. Can we continue to ship signatures for future releases, please?
Thanks a lot!

**Comment by LudovicRousseau** [comment]
I added the GnuPG signature of the `.tar.gz` in https://sourceforge.net/projects/pyscard/files/pyscard/pyscard%201.9.5/

I hope that is what you expected.

**Comment by eworm-de** [comment]
Looks good. Thanks a lot!
