### ISSUE TITLE
Debian package is missing dependency

### ISSUE THREAD

**Issue by rugo** [LudovicRousseau/pyscard#42]
Hi,

I don't know if this belongs here, but after installing your package on Debian via

```
apt install python-pyscard
```

You get the error:

```
smartcard.pcsc.PCSCExceptions.EstablishContextException: 'Failure to establish context: Service not available.'
```
when using your library.

This is because the service pcscd is not installed. Which can easily be fixed of course.

My question now is, why the dependencies of the debian package:

```
Depends: libc6 (>= 2.14), python (>= 2.7), python (<< 2.8)
```

Do not contain pcscd?

My system:

```
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
```

Greets

**Comment by LudovicRousseau** [comment]
Debian bugs should be reported to https://bugs.debian.org.
I am also the Debian maintainer of all these packages so I can answer here.

libpcsclite1 https://packages.debian.org/sid/libpcsclite1 (used by python-pyscard) has a *suggest* dependency on pcscd.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=612971 to know why the dependency is not stronger.
