### ISSUE TITLE
SCARD_S_SUCCESS on mute card after SCardTransmit

### ISSUE THREAD

**Issue by KostiantynChertov** [LudovicRousseau/pyscard#44]
I tested my card application with pyscard lib on Win10 x64. When card (due to internal error) became mute after SCardTransmit, the lib returns SCARD_S_SUCCESS, probably after a timeout.

**Comment by LudovicRousseau** [comment]
PySCard just return the value returned by Windows WinSCard API.
I don't know what I can do for you.

**Comment by KostiantynChertov** [comment]
In this case I could just close the issue.
It's not a problem for me as I found at last my error :-)
