### ISSUE TITLE
Cannot send command to reader

### ISSUE THREAD

**Issue by masterandrey** [LudovicRousseau/pyscard#51]
For example Get firmware version as described on
https://www.acs.com.hk/en/products/159/acr1281u-c1-dualboost-ii-usb-dual-interface-reader/

There should be separate way to send command not to card but to reader (pc to RDR escape as in ACR documentation).
This is APDU commands so I cannot use doCommand that send one code.

In fact I am looking for a way to communicate with SAM (secure access module) installed on the reader.
I can communicate with card in proximity with the reader but see no way to execute reader commands specifically to select SAM.

**Comment by LudovicRousseau** [comment]
Have a look at this code https://anonscm.debian.org/cgit/pcsclite/PCSC.git/tree/UnitaryTests/FEATURE_CCID_ESC_COMMAND_Xiring.py

**Comment by masterandrey** [comment]
Thank you!

**Comment by masterandrey** [comment]
Is that possible connect to the SAM interface in the smartcard library?
In ACR documentation this is described as SCardConnect(... 'ACR128U SAM Interface'...)

**Comment by LudovicRousseau** [comment]
Yes, it is.

**Comment by masterandrey** [comment]
How to do that? I do not understand how to pass interface name
