### ISSUE TITLE
Installation error on Mac High Sierra

### ISSUE THREAD

**Issue by yika1999** [LudovicRousseau/pyscard#56]
I got errors while I'm trying to install pyscard 1.9.6 with Python 3.6.4 on my Mac - High Sierra 
pcsctest worked fine. 
---------------------------------------------------------------------------
In file included from smartcard/scard/winscarddll.c:26:
smartcard/scard/winscarddll.h:280:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszReaders,
            ^
smartcard/scard/winscarddll.h:286:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszGroups,
            ^
smartcard/scard/winscarddll.h:304:9: error: unknown type name 'LPTSTR'
    OUT LPTSTR szReaderName,
        ^
smartcard/scard/winscarddll.c:529:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszReaders,
            ^
smartcard/scard/winscarddll.c:543:13: error: unknown type name 'LPTSTR'
    OUT     LPTSTR mszGroups,
            ^
smartcard/scard/winscarddll.c:582:9: error: unknown type name 'LPTSTR'
    OUT LPTSTR szReaderName,

**Comment by LudovicRousseau** [comment]
I can't reproduce the problem.
``LPTSTR`` is defined in ``/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/PCSC.framework/Headers/wintypes.h``

Maybe you have a problem with your setup.

**Comment by yika1999** [comment]
Thanks.
I reinstalled MacOSX and no problem at all.
