### ISSUE TITLE
binary wheels on pypi.org

### ISSUE THREAD

**Issue by dagheyman** [LudovicRousseau/pyscard#58]
Hello, thanks for a great project.
Is there any chance to get the binary wheels built for windows published on pypi.org?
It would allow [installation with pip](https://github.com/LudovicRousseau/pyscard/issues/55) without having swig installed.

**Comment by LudovicRousseau** [comment]
I do not provide binary packages (except the official Debian packages).
I also do not use Windows myself so I could not test the generated wheels.

You can get Windows binary installers from the AppVeyor page at https://ci.appveyor.com/project/LudovicRousseau/pyscard
For example https://ci.appveyor.com/project/LudovicRousseau/pyscard/build/job/m22dujrwu46yh2dh/artifacts for the Python 3.6 64 bits.

**Comment by LudovicRousseau** [comment]
I uploaded the wheels for Python 2.7 and Python 3.6 for amd64.

Unfortunately it is not possible to automate this so you will have to ping me again the next time I forget to upload windows wheels.

Thanks for the idea and sorry for the delay.
