### ISSUE TITLE
Inconsistent state after unexpected disconnect

### ISSUE THREAD

**Issue by whyscream** [LudovicRousseau/pyscard#63]
We have developed a simple smartcard using application, but are having issues when the nfc card is removed too soon.

Setup: Ubuntu 16.04 (pcscd 1.8.14, libnfc5 1.7.1, libccid 1.14.22), ACS122U nfc reader, Mifare classic nfc cards. 

We try to detect an available NFC card by:

```
cardrequest = CardRequest(timeout=1, cardType=AnyCardType())
cardservice = cardrequest.waitforcard()
cardservice.connection.connect()
cardservice.connection.getATR()
```

After a successful connection we can authenticate, read the tag, and decrement it.
But when we remove the card from the reader too soon, the transaction breaks (most of the time during the authentication). However, when we try to check for subsequent presented cards, the above routine successfully connects and returns without errors, also when no card is actually present. 

After the above situation, authenticating with the card fails, and our code crashes. How would we detect correctly whether a card is presented?

I also installed the upstream drivers from https://www.acs.com.hk/en/driver/3/acr122u-usb-nfc-reader/, but this makes no difference.

**Comment by LudovicRousseau** [comment]
I would need pcsc-lite logs as described in https://ccid.apdu.fr/#support
In the logs indicate the moment you removed the card.

You can also use pcsc_scan (from the Ubuntu pcsc-tools package) to check if the card events are correctly reported.

**Comment by whyscream** [comment]
Package versions:
- `libccid: 1.4.22-1ubuntu0.1`
- `pcscd: 1.8.14-1ubuntu1.16.04.1`
```
# pcscd --version
pcsc-lite version 1.8.14.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2011 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <muscle@lists.musclecard.com>.
Enabled features: Linux x86_64-pc-linux-gnu serial usb libudev usbdropdir=/usr/lib/pcsc/drivers ipcdir=/var/run/pcscd configdir=/etc/reader.conf.d
```
Platform:
- OS: Ubuntu 16.04.4 LTS (xenial)
- Hardware: Custom PC using `Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz`, 2GB ram
- smart card reader: vendor: `ACS`, model: `ACR122U`, version: `2.14`
- smart card type: `pcsc_scan` tells me this:
```
Thu Jul 19 09:26:41 2018
Reader 0: ACS ACR122U PICC Interface 00 00
  Card state: Card inserted, 
  ATR: 3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00 6A
ATR: 3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00 6A
+ TS = 3B --> Direct Convention
+ T0 = 8F, Y(1): 1000, K: 15 (historical bytes)
  TD(1) = 80 --> Y(i+1) = 1000, Protocol T = 0 
-----
  TD(2) = 01 --> Y(i+1) = 0000, Protocol T = 1 
-----
+ Historical bytes: 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00
  Category indicator byte: 80 (compact TLV data object)
    Tag: 4, len: F (initial access data)
      Initial access data: 0C A0 00 00 03 06 03 00 01 00 00 00 00
+ TCK = 6A (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00 6A
3B 8F 80 01 80 4F 0C A0 00 00 03 06 .. 00 01 00 00 00 00 ..
	Mifare Standard 1K (as per PCSC std part3)
3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00 6A
3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 .. .. 00 00 00 00 ..
	RFID - ISO 14443 Type A Part 3 (as per PCSC std part3)
3B 8F 80 01 80 4F 0C A0 00 00 03 06 03 00 01 00 00 00 00 6A
	Philips MIFARE Standard (1 Kbytes EEPROM)
	http://www.nxp.com/#/pip/pip=[pfp=41863]|pp=[t=pfp,i=41863]
	RFID - ISO 14443 Type A - Transport for London Oyster
	ACOS5/1k Mirfare
	RFID - ISO 14443 Type A - NXP Mifare card with 1k EEPROM
	vivotech ViVOcard Contactless Test Card
	Bangkok BTS Sky SmartPass
```

Log file from pcscd: [pcscd-log.txt](https://github.com/LudovicRousseau/pyscard/files/2209148/pcscd-log.txt). What I'm making of this:
- Startup the daemon, init of reader, no card present
- I try a few transactions until I can trigger the behaviour. The problematic behaviour starts at line 8795.
- Card is inserted and dected, ATR is retrieved (line 8819).
- I send command 'Load Authentication Keys', and this is successful (line 8856).
- I send command 'Authenticate Data Bytes' and this fails (line 8867). This is because I removed the card.
- I'm getting the State again, unsure what the response is (line 8875). The application code tries to get the ATR here again, which is successful (but this seems invisible in the logging).
- I send the command 'Load Authentication Keys' again, which succeeds (line 8888). (but there is no card?)
- I send the command  'Authenticate Data Bytes'  again, which fails (line 8899).
- This (State, load auth keys, auth data bytes) repeats until I exit the application code (line 10386), and the client goes away.
- After the client goes away, pcscd still thinks the card is present (line 10410), but after polling (line 10414) decides that the card is gone (line 10418).

My conclusions so far:
- `NotifySlotChange` detects whether the card is present, but when a client is connected to the card, this isn't triggered, even when the card goes away.
- the ATR is only retrieved when upon first connection between card and reader, and returned from cache upon subsequent requests for the ATR. This makes requesting the ATR not a valid way to detect whether the card is still present.

So what is the correct way to detect that the card is no longer present mid-transaction? And the correct way to reconnect when the card is presented again? Shoudl I simply kill and reconnect my client after any error?

**Comment by LudovicRousseau** [comment]
Great debug details.
Some more information:
- the reader sends interrupts to signal a card change. The interrupt messages are managed by `NotifySlotChange`. So unless the reader sends a new slot change notification then pcscd consider the card state has not changed.
- the ATR is retrieve only during the card power up. The ATR is not supposed to change after that so pcscd does not ask the card (with a new power up) to get the ATR value. A cache is used.
- the APDU commands you use are for the reader, not for the card. So it is normal that the 'Load Authentication Keys' works fine even if no card is present.
- a contactless reader does not have a physical contact to detect a card "insertion" or a card "removal". 
- the reader will not report a card removal just at the time of the removal, but sometime after that (depending in the reader firmare, etc.)
- use pcsc_scan to know how the reader behaves regarding card events
- to detect a card is present you should use SCardStatus() https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382 or SCardGetStatusChange() https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
