### ISSUE TITLE
Pyinstaller fails with pyscard on windows

### ISSUE THREAD

**Issue by dagheyman** [LudovicRousseau/pyscard#65]
I just ran into the issue described here:

https://stackoverflow.com/questions/49718551/pyinstaller-fails-with-pyscard-on-windows

Do you think that it is something that is possible to adress on the pyscard side?

**Comment by LudovicRousseau** [comment]
PySCard uses an native library built during installation.
I don't know if Pyinstaller can support that. It looks like a solution is documented in the stackoverflow question you mention.

If you know how to make PySCard work for you then please submit a patch.
