### ISSUE TITLE
Circuit diagram for the smart card reader code

### ISSUE THREAD

**Issue by ronie19** [LudovicRousseau/pyscard#68]
Hello, can you pls provide a circuit diagram for interface contact based smart card/SIM card with raspberry pi ??? 
Thanks in advance.

**Comment by LudovicRousseau** [comment]
No.

**Comment by ronie19** [comment]
Is it USB based reader ? Or some other arrangement....I am new learner , wanted to know

**Comment by LudovicRousseau** [comment]
If you are looking for a smart card reader for your RaspberryPi you can have a look at https://ccid.apdu.fr/ccid/supported.html and buy one from the list.

**Comment by ronie19** [comment]
I may not get my hands on the listed... Just wanted to know if a generic USB SIM card reader may work or not ? As sim cards are smart cards themselves .
