### ISSUE TITLE
Card is unpowered

### ISSUE THREAD

**Issue by BiohazardShell** [LudovicRousseau/pyscard#72]
I  just receive a reader and "blank" cards from wish (I know not the best place).
Will testing it using pyscard ( I'm using the python-pyscard) and working my way around to get the reader working. (I solve all the issue by installing python-usb and pcscd packets btw).
I get that : 
`In [1]: from smartcard.System import readers
In [2]: readers()
Out [2]: ['Alcor Micro AU9560 00 00']
In [3]: r = readers()
In [4]: c = r[0].createConnection()
In [5]: c.connect()
NoCardException: ('Unable to connect to card or no cardin reader', 'Unable to connect: No smart card inserted.')`
I insert the card because now I know the reader is working.
`In [6]: c.connect()
CardConnectionException: Unable to connect with protocol: T0 or T1. Card is unpowered.`
Any ideas where it comes from ? 
Should I try compling the git project ?

**Comment by BiohazardShell** [comment]
I've complied the git and still the same card unpowered error.

**Comment by BiohazardShell** [comment]
the "blank" cards use siemens sle4442 chip.
if you need it : [https://e-scan.com/sle4442.pdf](https://e-scan.com/sle4442.pdf)

**Comment by BiohazardShell** [comment]
never mind ... the reader only support 8 contacts cards , I was using 6 contacts ones ...
My bad.

**Comment by LudovicRousseau** [comment]
SLE4442 are memory cards, not microprocessor cards.

**Comment by BiohazardShell** [comment]
oh! didn't know that ! thanks . I'm new to that stuff
