### ISSUE TITLE
Plugout an PCSC device will raise ListReadersException(hresult) on windows

### ISSUE THREAD

**Issue by leileigong** [LudovicRousseau/pyscard#74]
I use pyscard-1.9.17, but i got an problem which is similar to several.
1)[Exception ListReadersException raised after disconnecting PCSC reader #13 ](https://github.com/LudovicRousseau/pyscard/issues/13)
2)[Stop CardMonitor monitor thread after traceback print. #22 ](https://github.com/LudovicRousseau/pyscard/pull/22)

I guess that #13  #22 do not fixed the problem.

Here is my traceback info:

Traceback (most recent call last):
File "C:\Users\lei.virtualenvs\TestTool-gkAj8wo0\lib\site-packages\smartcard\CardMonitoring.py", line 162, in run
currentcards = self.cardrequest.waitforcardevent()
File "C:\Users\lei.virtualenvs\TestTool-gkAj8wo0\lib\site-packages\smartcard\CardRequest.py", line 73, in waitforcardevent
return self.pcsccardrequest.waitforcardevent()
File "C:\Users\lei.virtualenvs\TestTool-gkAj8wo0\lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 288, in waitforcardevent
readernames = self.getReaderNames()
File "C:\Users\lei.virtualenvs\TestTool-gkAj8wo0\lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 90, in getReaderNames
raise ListReadersException(hresult)
ListReadersException: ('Failed to list readers', -2146435042L)

**Comment by leileigong** [comment]
this problem trap on win10 ,  but work fine on win7

**Comment by LudovicRousseau** [comment]
-2146435042L is 0x8010001E and is `SCARD_E_SERVICE_STOPPED`

What should be the expected behaviour for you?

**Comment by leileigong** [comment]
After i plug in a device, the pyscard service should not stop.

**Comment by LudovicRousseau** [comment]
PySCard does not stop, but raises an exception.

When a reader is plugged IN no exception is raised.
My question is what should happen when a reader is plugged OUT.

**Comment by leileigong** [comment]
When a reader is plugged OUT, ScardListReader methord should not raise an exception.But now it raises SCARD_E_SERVICE_STOPPED

**Comment by LudovicRousseau** [comment]
The exception `SCARD_E_SERVICE_STOPPED` is not raised by `SCardListReaders()` but by `getReaderNames()` https://github.com/LudovicRousseau/pyscard/blob/master/smartcard/pcsc/PCSCCardRequest.py#L84

`getReaderNames()` returns a list of reader(s). The only way for it to return an error is by throwing an exception.

What should `getReaderNames()` do instead?

**Comment by leileigong** [comment]
After reader is pluged OUT, the windows smartcard service does not really stop, so getReaderNames() should not raise an exception, it should return a list of  reader(s).

**Comment by LudovicRousseau** [comment]
I don't know if PC/SC manager really stopped or not. But `SCardListReaders()` returned `SCARD_E_SERVICE_STOPPED`. I don't think PySCard should just ignore this error code.

Do you get the error/exception if you have 2 reader connected and disconnect one, or only when you disconnect the **last** reader?

**Comment by leileigong** [comment]
i just have one reader contected, if it is plugged OUT, SCardListReaders() should not return an error but return an empty list .

**Comment by leileigong** [comment]
I got an new tips. 
If you have 2 reader connected and disconnect one, i do not get an error/exception.
But if disconnect the **last** reader, then SCardListReaders() returned SCARD_E_SERVICE_STOPPED.

**Comment by LudovicRousseau** [comment]
I expected this behaviour with 2 readers.

I propose you to:
- handle the exception in your code
- report your problem to Microsoft so they can fix it. See https://docs.microsoft.com/en-us/windows/desktop/api/winscard/nf-winscard-scardlistreadersa

**Comment by leileigong** [comment]
OK,thanks,you help a lot.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/pyscard/commit/bf906d3bc00bc929b05a3a10aabcf349138032d6
