### ISSUE TITLE
Regarding generic phoenix reader

### ISSUE THREAD

**Issue by ronie19** [LudovicRousseau/pyscard#79]
I came across this schematic using FT232RL usb to TTL converter. The link is here http://conture.by/post/1228
I made this at home. I am getting proper response after pcsc_scan. But when any code involves trasmit, then it fails to transmit. As a sim card reader it is working fine. Is there any tweaking to be done like active high or low reset ? All i am trying to make a small interface using open hardware and open software.

**Comment by LudovicRousseau** [comment]
This is not a pyscard issue.
I can’t help.
