### ISSUE TITLE
get card UUID 

### ISSUE THREAD

**Issue by sherifshsffa91** [LudovicRousseau/pyscard#84]
is there a way to get uuid of read cards while I succesffuly installed pyscard on raspberry pi

**Comment by LudovicRousseau** [comment]
Yes, I guess there is a way.
No idea how.

**Comment by fananimi** [comment]
@sherifshsffa91 read the [documentation](https://pyscard.sourceforge.io/)  carefully before asking the question.  And please to understand the concept of APDU first.  The APDU command how to get UID of some cards may different, so you need to follow APDU documentation of your card.

This may help you.
