### ISSUE TITLE
Reader turning off after removing card, won't turn back on until program restarts

### ISSUE THREAD

**Issue by tmello01** [LudovicRousseau/pyscard#86]
Hello!

I am using the ACR122u card reader with pyscard, and currently for single tags at a time it works fantastic. However, in an infinite loop, if a card is removed the reader will not connect again and requires the program restarting in order to get one more read. This happens continually. Here is the code to connect and read from the tag:

```python
def CheckNFCCard():
    getUIDCommand = [0xFF, 0xCA, 0x00, 0x00, 0x00]
    turnOffBeepCommand = [0xFF, 0x00, 0x52, 0x00, 0x00]
    getDataCommand = [0xFF, 0xB0, 0x00, 0x07, 0x10]
    updateBlockCommandFirst=[0xFF, 0xD6, 0x00, 0x07, 0x04, 0x65, 0x6E, 0x75, 0x73]
    updateBlockCommandSecond=[0xFF, 0xD6, 0x00, 0x08, 0x04, 0x65, 0x64, 0xFE, 0x00]
  
  #get NFC reader
    r = readers()
    reader = r[0]
    #select reader, connect
    conn = reader.createConnection()
    while(True):
        print('NFC routine restart')
        try:
            conn.connect()
        except:
            time.sleep(1)
            continue
        #send hex command to turn off beeps on scan.
        conn.transmit(turnOffBeepCommand)
        
        #get data encoded on tag.
        data, sw1, sw2 = conn.transmit(getDataCommand)
        if (sw1, sw2) == (0x90, 0x0):
            print("Status: The operation completed.")
        
        #Turn decimal numbers into characters
        stringList = [chr(x) for x in data]
        #
        identifierString = ''.join(stringList)[2:6]
        if (identifierString == "used"):
            pub.sendMessage('NFCDetected', arg1='used')
        elif (identifierString == "new_"):
            data, sw1, sw2 = conn.transmit(updateBlockCommandFirst)
            if (sw1, sw2) == (0x90, 0x0):
                conn.transmit(updateBlockCommandSecond)
            Thread(target=pub.sendMessage, args=('NFCDetected',), kwargs={'new' : arg1}).Start()
        time.sleep(1)
        continue
```

This works great the first time. After that first read, the reader stops reading, but the while loop continues to run. Am I approaching this library wrong?

**Comment by LudovicRousseau** [comment]
Yes.

**Comment by tmello01** [comment]
Sorry, could you elaborate? I thought I followed the documentation but apparently not haha.

**Comment by LudovicRousseau** [comment]
You should wait for a card insertion before you try to connect to it.

But the program should not fail in your case.
What operating system do you use?

**Comment by tmello01** [comment]
Is there a way to set up an event of some sort that'll alert me when a card is inserted so I can connect to the reader? This is a case where I would be waiting for the user to insert a card without knowing when they are going to do it. 

I am running this on a Raspberry Pi running Raspbian Buster.

**Comment by LudovicRousseau** [comment]
Monitoring Smart Cards
https://pyscard.sourceforge.io/user-guide.html#monitoring-smart-cards

Generate a pcscd trace as documented at https://pcsclite.apdu.fr/#support

**Comment by tmello01** [comment]
Here is the pcscd trace: https://pastebin.com/ReZRDsJD

**Comment by tmello01** [comment]
For some context on that trace, that was after adding a card to the reader, leaving it there for 2-3 seconds, removing it, and letting the logs run for a bit afterward.

**Comment by LudovicRousseau** [comment]
I do not see any error in this pcscd trace.
I also see that you added a card but never removed it. Exact?
You also NEVER disconnect from the reader. After one point any new connection will fail.
