### ISSUE TITLE
module smartcard.util not found when running osmo-sim-auth.py 

### ISSUE THREAD

**Issue by abiodunwuyi** [LudovicRousseau/pyscard#89]
Please, kindly suggest how to fix below error;

(venv) [root@ibm044 osmo-sim-auth]# ./osmo-sim-auth.py --help
Traceback (most recent call last):
  File "./osmo-sim-auth.py", line 25, in <module>
    from card.utils import *
  File "/root/work-dir/venv/osmo-sim-auth/card/utils.py", line 26, in <module>
    from smartcard.util import toBytes
ImportError: No module named smartcard.util
![smartcard_util error](https://user-images.githubusercontent.com/25392833/73570200-e5f3b480-4439-11ea-802f-180b837d2574.PNG)

**Comment by LudovicRousseau** [comment]
Maybe you need to install pyscard?
Why do you ask here for an osmo-sim-auth issue?

**Comment by abiodunwuyi** [comment]
pyscard is already installed with "Requirements already satisfied", but the error still persists.

**Comment by LudovicRousseau** [comment]
What is the output of 
```python -c 'import smartcard'```
and
```python -c 'import smartcard.util'```

**Comment by abiodunwuyi** [comment]
![import smartcard error](https://user-images.githubusercontent.com/25392833/73663096-ee7f0180-466a-11ea-8a83-326287362134.PNG)

**Comment by LudovicRousseau** [comment]
it confirms that pyscard is NOT installed, or not installed correctly.

**Comment by abiodunwuyi** [comment]
So I have to uninstall and reinstall it?

**Comment by LudovicRousseau** [comment]
I can do paied consulting if you need.
This is NOT an issue with pyscard.

**Comment by bbaranoff** [comment]
sorry to answer to a thing that is not really an issue but worked for me
sudo apt install -y python3-pip pcscd pcsc-tools libpcsclite-dev python3-pyscard python3-cmd2
pip3 install contruct jsonpath-ng pytlv

**Comment by LudovicRousseau** [comment]
You only need to install the `python3-pyscard` package.
But I guess @abiodunwuyi was not using a Debian (or derivative) system.

**Comment by bbaranoff** [comment]
Was thinking about pySim-read.py from osmocom but that's not the place but became here first when googling error... Sorry goodbye

**Comment by bbaranoff** [comment]
I think this is an osmocom issue reason for what Ludovic closed this.
Have you installed all PySim dependencies 
![Screenshot_2024-06-14-13-00-20-62_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/LudovicRousseau/pyscard/assets/37385191/0d5c5d42-eed3-46d0-924e-d26265b680d8)

**Comment by LudovicRousseau** [comment]
@bbaranoff what is the result of:
```
cd
python3 -c "import smartcard.util"
```

I guess you are using Debian stable. Exact?

**Comment by LudovicRousseau** [comment]
@tomislavmiksa  what is the result of:
```
cd
python3 -c "import smartcard.util"
```

I guess you are using Debian stable. Exact?
