### ISSUE TITLE
pyscard in python flask web base

### ISSUE THREAD

**Issue by BoyAbdullah** [LudovicRousseau/pyscard#92]
any possible to use pyscard for web base, when i try to connect to NFC device on client site but application always show message NoneType

**Comment by LudovicRousseau** [comment]
If you can do PC/SC over the web then it should work.

**Comment by BoyAbdullah** [comment]
work when i try from local base (development site), but on client server base (client site) its not working. i'm using python flask blueprint with wsgi in xampp

**Comment by LudovicRousseau** [comment]
I can do consulting if you want. Contact me by email.

**Comment by BoyAbdullah** [comment]
> I can do consulting if you want. Contact me by email.

may i have ur email address sir?

**Comment by LudovicRousseau** [comment]
Sorry. I thought it was available on my profile. ludovic.rousseau@free.fr

**Comment by fananimi** [comment]
> work when i try from local base (development site), but on client server base (client site) its not working. i'm using python flask blueprint with wsgi in xampp
> 
> maybe you have configuration for client server side like using ip address and port?
> 
> for example code:
> ```python
>     @staticmethod
>     def nfcSerial():
>         serial = None
> 
>         cardtype = AnyCardType()
> 
>         try:
> 
>             cardrequest = CardRequest(timeout=10, cardType=cardtype)
>             cardservice = cardrequest.waitforcard()
> 
>             observer = ConsoleCardConnectionObserver()
>             cardservice.connection.addObserver(observer)
> 
>             cardservice.connection.connect()
> 
>             chip_beep_mute = "ff00520000"
>             chip_beep_unmute = "ff0052ff00"
>             apdu = [int(chip_beep_mute[i:i + 2], 16) for i in range(0, len(chip_beep_mute), 2)]
>             response, sw1, sw2 = cardservice.connection.transmit(apdu)
> 
>             chip_info_serial = "ffca000000"
>             apdu = [int(chip_info_serial[i:i + 2], 16) for i in range(0, len(chip_info_serial), 2)]
>             response, sw1, sw2 = cardservice.connection.transmit(apdu)
>             if sw1 == 0x90:
>                 serial = toHexString(response)
>             else:
>                 serial = None
> 
>             print(serial)
>         except CardRequestTimeoutException:
>             serial = None
>         except:
>             serial = None
> 
>         return serial
> ```

@BoyAbdullah 

I have experience in web development through dekstop programming like xampp in here https://github.com/fananimi/IotBox-Hack.

And here sample of my pyscard with Qt https://github.com/fananimi/mifare-tools

Don't hesitate , may I can help you. 

Thanks.
