### ISSUE TITLE
Issue with ACR-122U

### ISSUE THREAD

**Issue by mzeitler** [LudovicRousseau/pyscard#94]
I have a strange issue with the ACR-122U reader on Raspbian Buster.

Even though the device is recognized with lsusb, I get infrequent errors. It works until an error appears. Once an error appears I need to unplug the USB and plug it back in to get t working again. In most cases this solves it. Or I have to replug again. Rebooting doesnt solve the issue though.

I have blacklisted pn533 as this was recommended elsewhere
/etc/modprobe.d/blacklist-libnfc.conf
blacklist pn533_usb
blacklist nfc

 
lsusb
Bus 001 Device 006: ID 072f:2200 Advanced Card Systems, Ltd ACR122U

from /var/log/syslog
May 20 14:37:15 lockgondolainside pcscd[15936]: 20658019 ccid_usb.c:898:ReadUSB() read failed (1/6): -7 LIBUSB_ERROR_TIMEOUT
May 20 14:37:15 lockgondolainside pcscd[15936]: 00000130 ifdwrapper.c:364:IFDStatusICC() Card not transacted: 612
May 20 14:37:15 lockgondolainside pcscd[15936]: 00000064 eventhandler.c:336:EHStatusHandlerThread() Error communicating to: ACS ACR122U PICC Interface 00 00

How can I get rid of this error make to make the reading of tokens more reliable?

**Comment by LudovicRousseau** [comment]
This is NOT an issue with pyscard.

I don't know what driver you are using. Maybe https://github.com/acshk/acsccid would fix your problem.
