### ISSUE TITLE
Any support for SPI connected PN532  NFC devices ?

### ISSUE THREAD

**Issue by ronie19** [LudovicRousseau/pyscard#97]
If any support for the SPI connected PN532  NFC devices then kindly update the procedure for the same.

**Comment by LudovicRousseau** [comment]
If the reader is available at the PC/SC (WinSCard) level then it should work with pyscard.

**Comment by LudovicRousseau** [comment]
Please do NOT spam my CCID project with questions about your reader.
https://github.com/LudovicRousseau/CCID/commit/94bddf6e40fa1e75f934e299d24fe126f4f91b68#commitcomment-41313719
