### ISSUE TITLE
Add libpcsclite-dev to system requirements

### ISSUE THREAD

**Issue by k0s3r40** [LudovicRousseau/pyscard#99]
Can you add libpcsclite-dev to system requirements. For the people in the feauture which encounter this error:
> card/helpers.c:28:10: fatal error: winscard.h: No such file or directory

or handle the error:
> libpsclite-dev is not insalled.
> Please run sudo apt-get install libpcsclite-dev

**Comment by LudovicRousseau** [comment]
`libpcsclite-dev` is the name of the Debian/Ubuntu package. For RedHat/CentOS it is `pcsc-lite-devel`.
For Windows I don't know. For macOS it is installed with Xcode.

What patch do you propose to support all these systems?

**Comment by LudovicRousseau** [comment]
Please come back with a solution if you have one.
